// =============================================================================
// EMP UA Helper — LocalizationService.cs
// Автор / Author: EMP_UA (https://github.com/EMP-UA/EMP-UA-Helper)
// Підтримати / Donate: https://ko-fi.com/emp_ua
// Ліцензія / License: GPL-3.0
// =============================================================================
// UA: Сервіс локалізації інтерфейсу (UA/EN)
// EN: UI localization service (UA/EN)
// =============================================================================
namespace EMP.UAHelper.Core.Services
{
    public enum UiLanguage { UA, EN }

    public class LocalizationService
    {
        public UiLanguage Language { get; private set; } = UiLanguage.UA;

        public event Action? LanguageChanged;

        public void SetLanguage(UiLanguage language)
        {
            Language = language;
            LanguageChanged?.Invoke();
        }

        public string Get(string key) =>
            Language == UiLanguage.UA
                ? UA.TryGetValue(key, out var ua) ? ua : key
                : EN.TryGetValue(key, out var en) ? en : key;

        private static readonly Dictionary<string, string> UA = new()
        {
            ["app.name"] = "EMP UA Helper",
            ["app.save"] = "💾 Зберегти",
            ["app.cancel"] = "Скасувати",
            ["app.exit"] = "Вихід",
            ["app.success"] = "Успіх",
            ["app.error"] = "Помилка",
            ["app.warning"] = "Увага",
            ["app.yes"] = "Так",
            ["app.no"] = "Ні",

            ["tray.send"] = "📡 Надіслати сповіщення",
            ["tray.edit_templates"] = "✏️ Редагувати шаблони",
            ["tray.settings"] = "⚙️ Налаштування",
            ["tray.exit"] = "Вихід",
            ["tray.checking"] = "EMP UA Helper — Перевірка...",
            ["tray.no_result"] = "YouTube API не повернув жодного результату.",
            ["tray.sending"] = "Відправка сповіщень у Telegram та Discord...",
            ["tray.sent"] = "Сповіщення надіслано.",
            ["tray.started"] = "EMP UA Helper запущено.",
            ["tray.stopped"] = "EMP UA Helper завершено.",

            ["type.live"] = "🟢 Трансляція",
            ["type.upcoming"] = "🔔 Анонс",
            ["type.video"] = "💾 Відео",
            ["type.short"] = "⚡ Шортс",

            ["firstrun.title"] = "EMP UA Helper — Перший запуск",
            ["firstrun.welcome"] = "Ласкаво просимо до EMP UA Helper",
            ["firstrun.description"] = "Заповніть налаштування для потрібних вам платформ. Це можна будь-коли змінити пізніше через трей → «⚙️ Налаштування» — без перезапуску програми.",
            ["firstrun.save"] = "💾 Зберегти та запустити",
            ["firstrun.validation"] = "Будь ласка, заповніть усі поля увімкнених платформ.",
            ["firstrun.validation.platform"] = "Оберіть принаймні одну платформу сповіщень: Telegram або Discord.",
            ["firstrun.section.telegram"] = "TELEGRAM",
            ["firstrun.section.youtube"] = "YOUTUBE",
            ["firstrun.section.discord"] = "DISCORD",
            ["firstrun.section.twitch"] = "TWITCH",
            ["firstrun.use.telegram"] = "Використовувати Telegram",
            ["firstrun.use.youtube"] = "Використовувати YouTube",
            ["firstrun.use.discord"] = "Використовувати Discord",
            ["firstrun.use.twitch"] = "Додавати посилання на Twitch",
            ["firstrun.tg.token"] = "Bot Token",
            ["firstrun.tg.token.hint"] = "@BotFather → /newbot або /token",
            ["firstrun.tg.channel"] = "Канал-отримувач",
            ["firstrun.tg.channel.hint"] = "Username каналу куди бот надсилає повідомлення",
            ["firstrun.yt.key"] = "API Key",
            ["firstrun.yt.key.hint"] = "console.cloud.google.com → Credentials → API Key → YouTube Data API v3",
            ["firstrun.yt.channelid"] = "Channel ID",
            ["firstrun.yt.channelid.hint"] = "youtube.com/@канал → Персоналізувати канал → URL-адреса каналу",
            ["firstrun.dc.webhook"] = "Webhook URL",
            ["firstrun.dc.webhook.hint"] = "Редагувати канал → Інтеграції → Вебхуки → Новий вебхук → Скопіювати URL",
            ["firstrun.dc.roleid"] = "Role ID (для пінгу)",
            ["firstrun.dc.roleid.hint"] = "Налаштування сервера → Ролі → ПКМ на роль → Копіювати ID ролі (потрібен режим розробника)",
            ["firstrun.tw.url"] = "Channel URL",
            ["firstrun.tw.url.hint"] = "https://www.twitch.tv/your_channel",

            ["settings.title"] = "EMP UA Helper — Налаштування",
            ["settings.header"] = "Налаштування платформ",
            ["settings.description"] = "Оберіть, які платформи активні саме сьогодні. Зміни застосовуються одразу, без перезапуску програми.",
            ["settings.save"] = "💾 Зберегти зміни",
            ["settings.group.general"] = "ЗАГАЛЬНЕ",
            ["settings.timezone.label"] = "Часовий пояс",
            ["settings.timezone.hint"] = "Використовується для всіх дат/часу трансляцій — у прикладах повідомлень, при виборі відео зі списку та в позначках часу для Discord/Telegram. Попередньо підставлена системна зона цього комп'ютера; збережене значення надалі не змінюється саме собою, навіть якщо системний час зміниться.",
            ["settings.group.content"] = "ДЖЕРЕЛА КОНТЕНТУ (де ви стрімите / публікуєте)",
            ["settings.group.notify"] = "ПЛАТФОРМИ СПОВІЩЕНЬ (куди надсилати анонси)",

            ["templates.title"] = "EMP UA Helper — Редактор шаблонів",
            ["templates.header"] = "Редактор шаблонів повідомлень",
            ["templates.hint"] = "Змінні: {title} — назва    {url} — YouTube    {twitch} — Twitch    {scheduled_telegram} — дата/час (Telegram, Upcoming)    {scheduled_discord} — Unix час (Discord, Upcoming)",
            ["templates.tab.telegram"] = "Telegram",
            ["templates.tab.discord"] = "Discord",
            ["templates.discord.title_label"] = "Заголовок",
            ["templates.discord.body_label"] = "Тіло",
            ["templates.reset"] = "↺ Скинути до defaults",
            ["templates.save"] = "💾 Зберегти",
            ["templates.saved"] = "Шаблони збережено успішно!",
            ["templates.reset.confirm"] = "Скинути всі шаблони до стандартних значень?",
            ["templates.reset.done"] = "Шаблони скинуто до стандартних значень.",
            ["templates.live"] = "🟢 Live — активна трансляція",
            ["templates.upcoming"] = "🔔 Upcoming — запланована трансляція",
            ["templates.video"] = "💾 Video — звичайне відео",
            ["templates.short"] = "⚡ Short — шортс",

            ["send.title"] = "EMP UA Helper — Надіслати сповіщення",
            ["send.header"] = "Надіслати сповіщення",
            ["send.description"] = "Перегляньте приклад повідомлення перед відправкою. За потреби вимкніть автопідбір і оберіть інше відео зі списку або введіть дані вручну.",
            ["send.auto_checkbox"] = "Надсилати за останнім опублікованим контентом",
            ["send.preview.label"] = "Приклад повідомлення",
            ["send.preview.empty"] = "Оберіть принаймні одну платформу сповіщень (Telegram або Discord), щоб побачити приклад.",
            ["send.picker.toggle"] = "🎬 Обрати відео зі списку",
            ["send.picker.change"] = "змінити",
            ["send.picker.loading"] = "Завантаження списку з YouTube…",
            ["send.picker.error"] = "Не вдалося завантажити список з YouTube. Можна ввести дані вручну нижче.",
            ["send.picker.offline"] = "Не вдалося оновитись з YouTube — показано збережений локально список. Деталі помилки в logs/.",
            ["settings.dc.webhook_name"] = "Назва основного каналу (необов'язково)",
            ["settings.dc.webhook_name.hint"] = "Підпис для вибору каналу у вікні надсилання. Якщо канал один — можна лишити порожнім.",
            ["settings.dc.extra_channels"] = "Додаткові канали Discord",
            ["settings.dc.extra_channels.hint"] = "Кожен рядок — назва і вебхук окремого каналу. Автоматичні сповіщення завжди йдуть в основний канал; ці потрібні лише щоб вручну надіслати кудись інше.",
            ["settings.dc.add_channel"] = "➕ Додати канал",
            ["settings.dc.remove_channel"] = "Видалити цей канал",
            ["send.raw.mention.label"] = "Згадка Discord — введіть лише ID",
            ["send.raw.mention.hint"] = "Вставте сам ID (тільки цифри) — готовий код згенерується нижче. У Discord: ПКМ по ролі/користувачу/каналу → «Копіювати ID» (потрібен режим розробника в налаштуваннях Discord).",
            ["send.raw.mention.snippet"] = "Готовий код — скопіюйте і вставте в текст",
            ["send.raw.mention.role"] = "Роль",
            ["send.raw.mention.user"] = "Користувач",
            ["send.raw.mention.channel"] = "Канал",
            ["send.channel.override"] = "Надіслати в інший канал Discord",
            ["send.channel.hint"] = "Типово повідомлення йде в основний канал. Список каналів налаштовується в «⚙️ Налаштування».",
            ["send.channel.primary_default"] = "Основний канал",
            ["send.channel.unnamed"] = "Канал без назви",
            ["send.picker.api_fallback.tooltip"] = "Спробувати через YouTube Data API замість RSS (витрачає добову квоту)",
            ["send.picker.api_fallback.confirm"] = "RSS-фід YouTube недоступний. Спробувати отримати список напряму через YouTube Data API?\n\nЦе витратить приблизно {0} одиниць добової квоти (типовий ліміт — 10 000 на добу, скидається щодоби). Безкоштовний RSS-шлях квоту не витрачає.\n\nПродовжити?",
            ["send.picker.api_fallback.done"] = "Список отримано через YouTube Data API (витрачено ~{0} одиниць квоти).",
            ["send.picker.hint"] = "Список включає останні записи з YouTube та раніше збережені заплановані трансляції — навіть ті, що вже випали з переліку останніх ~15 відео на каналі.",
            ["send.title_label"] = "Заголовок",
            ["send.type_label"] = "Тип",
            ["send.type_hint"] = "Категорія впливає лише на шаблон і колір сповіщення — не залежить від конкретної платформи.",
            ["send.url_label"] = "Посилання (необов'язково)",
            ["send.url_hint"] = "Якщо вказати посилання — воно підставиться замість {url} у шаблоні. Якщо залишити порожнім — рядки шаблону з {url} просто не увійдуть у повідомлення.",
            ["send.date_label"] = "Дата початку (дд.MM.рррр)",
            ["send.time_label"] = "Час початку (гг:хх, {0})",
            ["send.button"] = "📡 Надіслати",
            ["send.validation.title"] = "Введіть заголовок.",
            ["send.validation.datetime"] = "Введіть коректні дату і час у форматі дд.MM.рррр та гг:хх.",
            ["send.sent"] = "Сповіщення надіслано.",
            ["send.date_label.published"] = "Дата публікації",
            ["send.time_label.published"] = "Час публікації",
            ["send.url.warning"] = "Посилання не схоже на YouTube чи Twitch — перевірте, чи це правильна адреса.",
            ["send.preview.telegram"] = "Приклад — Telegram",
            ["send.preview.discord"] = "Приклад — Discord",
            ["send.thumbnail.twitch_note"] = "Прев'ю Twitch — неофіційне джерело (Twitch API вимагає авторизацію, якої ми уникаємо). Може не завантажитись або показувати застарілий стан каналу.",

            ["send.raw.toggle"] = "✍️ Повністю ручний режим (без шаблону)",
            ["send.raw.hint"] = "Жодних шаблонів і підстановок — відправляється рівно той текст, що ви ввели нижче, окремо для кожної платформи. Порожнє поле для платформи означає \"не надсилати туди\".",
            ["send.raw.telegram_label"] = "Текст для Telegram",
            ["send.raw.telegram_hint"] = "Підтримується HTML-форматування Telegram: <b>жирний</b>, <i>курсив</i>, <a href=\"...\">посилання</a>, <code>код</code>, <tg-spoiler>спойлер</tg-spoiler>. Незакриті теги призведуть до помилки відправки.",
            ["send.raw.discord_label"] = "Текст для Discord",
            ["send.raw.discord_hint"] = "Підтримується Markdown Discord: **жирний**, *курсив*, __підкреслення__, ~~закреслення~~, `код`. Теги: <@&ID_ролі> — згадати роль, <@ID_користувача> — згадати користувача, @everyone/@here. ID ролі можна взяти в налаштуваннях сервера (Роль → Копіювати ID, потрібен режим розробника). Ліміт — 2000 символів.",
            ["send.raw.validation.empty"] = "Введіть текст хоча б для однієї увімкненої платформи.",
            ["send.raw.empty_platforms"] = "Оберіть принаймні одну платформу сповіщень (Telegram або Discord) у налаштуваннях.",
            ["send.raw.scheduled.date_label"] = "Дата трансляції (дд.MM.рррр) — необов'язково",
            ["send.raw.scheduled.time_label"] = "Час трансляції (гг:хх, {0}) — необов'язково",
            ["send.raw.scheduled.hint"] = "Заповніть, якщо хочете отримати готові позначки часу нижче — під кожним текстовим полем зʼявиться рядок, який можна скопіювати й вручну вставити в потрібне місце повідомлення.",
            ["send.raw.scheduled.telegram_snippet"] = "Позначка часу — вставте в текст Telegram",
            ["send.raw.scheduled.discord_snippet"] = "Позначка часу — вставте в текст Discord",
        };

        private static readonly Dictionary<string, string> EN = new()
        {
            ["app.name"] = "EMP UA Helper",
            ["app.save"] = "💾 Save",
            ["app.cancel"] = "Cancel",
            ["app.exit"] = "Exit",
            ["app.success"] = "Success",
            ["app.error"] = "Error",
            ["app.warning"] = "Warning",
            ["app.yes"] = "Yes",
            ["app.no"] = "No",

            ["tray.send"] = "📡 Send notification",
            ["tray.edit_templates"] = "✏️ Edit templates",
            ["tray.settings"] = "⚙️ Settings",
            ["tray.exit"] = "Exit",
            ["tray.checking"] = "EMP UA Helper — Checking...",
            ["tray.no_result"] = "YouTube API returned no results.",
            ["tray.sending"] = "Sending notifications to Telegram and Discord...",
            ["tray.sent"] = "Notifications sent.",
            ["tray.started"] = "EMP UA Helper started.",
            ["tray.stopped"] = "EMP UA Helper stopped.",

            ["type.live"] = "🟢 Live stream",
            ["type.upcoming"] = "🔔 Upcoming stream",
            ["type.video"] = "💾 Video",
            ["type.short"] = "⚡ Short",

            ["firstrun.title"] = "EMP UA Helper — First Run",
            ["firstrun.welcome"] = "Welcome to EMP UA Helper",
            ["firstrun.description"] = "Fill in the settings for the platforms you need. You can change this anytime later via tray → \u201c⚙️ Settings\u201d — without restarting the app.",
            ["firstrun.save"] = "💾 Save and Launch",
            ["firstrun.validation"] = "Please fill in all fields for the enabled platforms.",
            ["firstrun.validation.platform"] = "Please select at least one notification platform: Telegram or Discord.",
            ["firstrun.section.telegram"] = "TELEGRAM",
            ["firstrun.section.youtube"] = "YOUTUBE",
            ["firstrun.section.discord"] = "DISCORD",
            ["firstrun.section.twitch"] = "TWITCH",
            ["firstrun.use.telegram"] = "Use Telegram",
            ["firstrun.use.youtube"] = "Use YouTube",
            ["firstrun.use.discord"] = "Use Discord",
            ["firstrun.use.twitch"] = "Include Twitch link",
            ["firstrun.tg.token"] = "Bot Token",
            ["firstrun.tg.token.hint"] = "@BotFather → /newbot or /token",
            ["firstrun.tg.channel"] = "Target Channel",
            ["firstrun.tg.channel.hint"] = "Channel username where the bot sends messages",
            ["firstrun.yt.key"] = "API Key",
            ["firstrun.yt.key.hint"] = "console.cloud.google.com → Credentials → API Key → YouTube Data API v3",
            ["firstrun.yt.channelid"] = "Channel ID",
            ["firstrun.yt.channelid.hint"] = "youtube.com/@channel → Customize channel → Channel URL",
            ["firstrun.dc.webhook"] = "Webhook URL",
            ["firstrun.dc.webhook.hint"] = "Edit Channel → Integrations → Webhooks → New Webhook → Copy URL",
            ["firstrun.dc.roleid"] = "Role ID (for mention)",
            ["firstrun.dc.roleid.hint"] = "Server Settings → Roles → Right-click role → Copy Role ID (requires Developer Mode)",
            ["firstrun.tw.url"] = "Channel URL",
            ["firstrun.tw.url.hint"] = "https://www.twitch.tv/your_channel",

            ["settings.title"] = "EMP UA Helper — Settings",
            ["settings.header"] = "Platform Settings",
            ["settings.description"] = "Choose which platforms are active today. Changes apply immediately, without restarting the app.",
            ["settings.save"] = "💾 Save changes",
            ["settings.group.general"] = "GENERAL",
            ["settings.timezone.label"] = "Timezone",
            ["settings.timezone.hint"] = "Used for all stream dates/times — in message previews, when picking a video from the list, and in the Discord/Telegram timestamp snippets. Pre-filled with this machine's system zone; the saved value never changes by itself afterward, even if the system clock's zone changes.",
            ["settings.group.content"] = "CONTENT SOURCES (where you stream / publish)",
            ["settings.group.notify"] = "NOTIFICATION PLATFORMS (where to send announcements)",

            ["templates.title"] = "EMP UA Helper — Template Editor",
            ["templates.header"] = "Message Template Editor",
            ["templates.hint"] = "Variables: {title} — title    {url} — YouTube    {twitch} — Twitch    {scheduled_telegram} — date/time (Telegram, Upcoming)    {scheduled_discord} — Unix time (Discord, Upcoming)",
            ["templates.tab.telegram"] = "Telegram",
            ["templates.tab.discord"] = "Discord",
            ["templates.discord.title_label"] = "Title",
            ["templates.discord.body_label"] = "Body",
            ["templates.reset"] = "↺ Reset to defaults",
            ["templates.save"] = "💾 Save",
            ["templates.saved"] = "Templates saved successfully!",
            ["templates.reset.confirm"] = "Reset all templates to default values?",
            ["templates.reset.done"] = "Templates reset to default values.",
            ["templates.live"] = "🟢 Live — active stream",
            ["templates.upcoming"] = "🔔 Upcoming — scheduled stream",
            ["templates.video"] = "💾 Video — regular video",
            ["templates.short"] = "⚡ Short — short video",

            ["send.title"] = "EMP UA Helper — Send Notification",
            ["send.header"] = "Send Notification",
            ["send.description"] = "Review the message preview before sending. Turn off auto-pick if you need to choose a different video from the list or enter details manually.",
            ["send.auto_checkbox"] = "Send based on the latest published content",
            ["send.preview.label"] = "Message preview",
            ["send.preview.empty"] = "Select at least one notification platform (Telegram or Discord) to see a preview.",
            ["send.picker.toggle"] = "🎬 Choose a video from the list",
            ["send.picker.change"] = "change",
            ["send.picker.loading"] = "Loading list from YouTube…",
            ["send.picker.error"] = "Couldn't load the list from YouTube. You can still enter details manually below.",
            ["send.picker.offline"] = "Couldn't refresh from YouTube — showing the locally cached list. Error details are in logs/.",
            ["settings.dc.webhook_name"] = "Primary channel name (optional)",
            ["settings.dc.webhook_name.hint"] = "A label for the channel picker in the send window. With a single channel it can stay empty.",
            ["settings.dc.extra_channels"] = "Additional Discord channels",
            ["settings.dc.extra_channels.hint"] = "Each row is the name and webhook of a separate channel. Automatic notifications always go to the primary channel; these exist only for manually sending somewhere else.",
            ["settings.dc.add_channel"] = "➕ Add channel",
            ["settings.dc.remove_channel"] = "Remove this channel",
            ["send.raw.mention.label"] = "Discord mention — enter the ID only",
            ["send.raw.mention.hint"] = "Paste just the ID (digits only) — the finished code is generated below. In Discord: right-click the role/user/channel → \"Copy ID\" (requires Developer Mode in Discord settings).",
            ["send.raw.mention.snippet"] = "Finished code — copy and paste it into the text",
            ["send.raw.mention.role"] = "Role",
            ["send.raw.mention.user"] = "User",
            ["send.raw.mention.channel"] = "Channel",
            ["send.channel.override"] = "Send to a different Discord channel",
            ["send.channel.hint"] = "By default the message goes to the primary channel. The channel list is configured in \"⚙️ Settings\".",
            ["send.channel.primary_default"] = "Primary channel",
            ["send.channel.unnamed"] = "Unnamed channel",
            ["send.picker.api_fallback.tooltip"] = "Try the YouTube Data API instead of RSS (spends daily quota)",
            ["send.picker.api_fallback.confirm"] = "The YouTube RSS feed is unavailable. Try fetching the list directly via the YouTube Data API?\n\nThis will spend roughly {0} units of the daily quota (the typical limit is 10,000 per day and resets daily). The free RSS path spends no quota.\n\nContinue?",
            ["send.picker.api_fallback.done"] = "List fetched via the YouTube Data API (~{0} quota units spent).",
            ["send.picker.hint"] = "The list includes recent YouTube entries plus previously cached scheduled streams — even ones that dropped out of the channel's last ~15 videos.",
            ["send.title_label"] = "Title",
            ["send.type_label"] = "Type",
            ["send.type_hint"] = "The category only affects the message template and color — it's not tied to any specific platform.",
            ["send.url_label"] = "Link (optional)",
            ["send.url_hint"] = "If you provide a link, it replaces {url} in the template. If left empty, template lines containing {url} are simply omitted.",
            ["send.date_label"] = "Start date (dd.MM.yyyy)",
            ["send.time_label"] = "Start time (HH:mm, {0})",
            ["send.button"] = "📡 Send",
            ["send.validation.title"] = "Please enter a title.",
            ["send.validation.datetime"] = "Enter a valid date and time in dd.MM.yyyy and HH:mm format.",
            ["send.sent"] = "Notification sent.",
            ["send.date_label.published"] = "Publish date",
            ["send.time_label.published"] = "Publish time",
            ["send.url.warning"] = "This link doesn't look like YouTube or Twitch — double-check the address.",
            ["send.preview.telegram"] = "Preview — Telegram",
            ["send.preview.discord"] = "Preview — Discord",
            ["send.thumbnail.twitch_note"] = "Twitch preview is unofficial (the Twitch API requires authorization, which we avoid). It may fail to load or show a stale channel state.",

            ["send.raw.toggle"] = "✍️ Fully manual mode (no template)",
            ["send.raw.hint"] = "No templates or substitution at all — sends exactly the text you type below, separately for each platform. An empty field for a platform means \"don't send there\".",
            ["send.raw.telegram_label"] = "Text for Telegram",
            ["send.raw.telegram_hint"] = "Telegram HTML formatting is supported: <b>bold</b>, <i>italic</i>, <a href=\"...\">link</a>, <code>code</code>, <tg-spoiler>spoiler</tg-spoiler>. Unclosed tags will cause the send to fail.",
            ["send.raw.discord_label"] = "Text for Discord",
            ["send.raw.discord_hint"] = "Discord Markdown is supported: **bold**, *italic*, __underline__, ~~strikethrough~~, `code`. Tags: <@&roleID> — mention a role, <@userID> — mention a user, @everyone/@here. Get the role ID from server settings (Role → Copy ID, requires Developer Mode). Limit — 2000 characters.",
            ["send.raw.validation.empty"] = "Enter text for at least one enabled platform.",
            ["send.raw.empty_platforms"] = "Select at least one notification platform (Telegram or Discord) in settings.",
            ["send.raw.scheduled.date_label"] = "Stream date (dd.MM.yyyy) — optional",
            ["send.raw.scheduled.time_label"] = "Stream time (HH:mm, {0}) — optional",
            ["send.raw.scheduled.hint"] = "Fill this in if you want ready-made timestamp snippets below — a copyable line will appear under each text field, which you can paste wherever needed in the message.",
            ["send.raw.scheduled.telegram_snippet"] = "Timestamp — paste into the Telegram text",
            ["send.raw.scheduled.discord_snippet"] = "Timestamp — paste into the Discord text",
        };
    }
}